export type STATUS_ENUM = 'ACTIVE' | 'INACTIVE' | 'BANNED';
export enum STATUS_ENUM_OPTIONS {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  BANNED = 'BANNED',
}

export type ADMIN_PERMISSION_ENUM = 'SUPERADMIN' | 'ADMIN';
export enum ADMIN_PERMISSION_ENUM_OPTIONS {
  SUPERADMIN = 'SUPERADMIN',
  ADMIN = 'ADMIN',
}

export type USER_TYPE_ENUM = 'STUDENT' | 'SENSEI' | 'ADMIN';
export enum USER_TYPE_ENUM_OPTIONS {
  STUDENT = 'STUDENT',
  SENSEI = 'SENSEI',
  ADMIN = 'ADMIN',
}
