export enum STATUS_ENUM {
  ACTIVE = 'ACTIVE',
  BANNED = 'BANNED',
}

export enum ADMIN_PERMISSION_ENUM {
  SUPERADMIN = 'SUPERADMIN',
  ADMIN = 'ADMIN',
}

export enum USER_TYPE_ENUM {
  STUDENT = 'STUDENT',
  SENSEI = 'SENSEI',
  ADMIN = 'ADMIN',
}

export enum PRIVACY_PERMISSIONS_ENUM {
  FOLLOWING_ONLY = 'FOLLOWING_ONLY',
  ALL = 'ALL',
  NONE = 'NONE',
}

export enum ADMIN_VERIFIED_ENUM {
  SHELL = 'SHELL',
  PENDING = 'PENDING',
  ACCEPTED = 'ACCEPTED',
  REJECTED = 'REJECTED',
}

export enum MENTORSHIP_PROGRESS_ENUM {
  NOT_STARTED = 'NOT_STARTED',
  ONGOING = 'ONGOING',
  CANCELLED = 'CANCELLED',
  COMPLETED = 'COMPLETED',
}

export enum MENTORSHIP_CONTRACT_APPROVAL {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
}
