export enum STATUS_ENUM {
  ACTIVE = 'ACTIVE',
  BANNED = 'BANNED',
}

export enum ADMIN_PERMISSION_ENUM {
  SUPERADMIN = 'SUPERADMIN',
  ADMIN = 'ADMIN',
}

export enum USER_TYPE_ENUM {
  STUDENT = 'STUDENT',
  SENSEI = 'SENSEI',
  ADMIN = 'ADMIN',
}

export enum PRIVACY_PERMISSIONS_ENUM {
  FOLLOWING_ONLY = 'FOLLOWING_ONLY',
  ALL = 'ALL',
}

export enum ADMIN_VERIFIED_ENUM {
  SHELL = 'SHELL',
  PENDING = 'PENDING',
  ACCEPTED = 'ACCEPTED',
  REJECTED = 'REJECTED',
}
