# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql
    container_name: database.dev
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    expose:
      - 3306
    environment:
      MYSQL_DATABASE: "node-db"
      MYSQL_USER: "administrator"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_TCP_PORT: 3306
    networks:
      - backend

networks:
  backend:
    driver: bridge