# Use root/example as user/password credentials
version: '3.1'

services:
  db:
    image: mysql/mysql-server:8.0.23
    container_name: database.dev
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - '25060:25060'
    expose:
      - 25060
    environment:
      MYSQL_DATABASE: 'defaultdb'
      MYSQL_USER: 'doadmin'
      MYSQL_PASSWORD: 'x94yr1ee6f5oovn9'
      MYSQL_ROOT_PASSWORD: 'x94yr1ee6f5oovn9'
      MYSQL_TCP_PORT: 25060
    networks:
      - backend

networks:
  backend:
    driver: bridge
