# Use root/example as user/password credentials
version: '3.1'

services:

  testdb:
    image: mysql
    container_name: database.test
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3307:3307"
    expose:
      - 3307
    environment:
      MYSQL_DATABASE: "test-db"
      MYSQL_USER: "administrator"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_TCP_PORT: 3307
    networks:
      - backend

networks:
  backend:
    driver: bridge